### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by shinux** [nodemailer/mailparser#208]
```
RangeError: Invalid string length
  File "/home/www/beast-mastery/node_modules/mailparser/lib/mailparser.js", line 179, in MailParser._write
    if (chunk && chunk.length) {
  File "/home/www/beast-mastery/node_modules/mailparser/lib/mailparser.js", line 125, in MailParser.write
    if (this._write(chunk, encoding)) {
  File "_stream_readable.js", line 542, in Readable.ondata
  File "events.js", line 77, in emitOne
  File "events.js", line 169, in Readable.emit
  File "_stream_readable.js", line 368, in Readable.read
  File "_stream_readable.js", line 759, in flow
  File "_stream_readable.js", line 739, in resume_
  File "node.js", line 458, in nextTickCallbackWith2Args
  File "node.js", line 413, in process._tickDomainCallback
```

**Comment by andris9** [comment]
Seems to be from an older version of Mailparser

**Comment by karunakargaddameedi** [comment]
code: '1',
      message: 'User profile updated successfully.' } ],
  OkPacket {
    fieldCount: 0,
    affectedRows: 0,
    insertId: 0,
    serverStatus: 34,
    warningCount: 0,
    message: '',
    protocol41: true,
    changedRows: 0 } ]
RangeError: Invalid string length
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at formatProperty (util.js:800:21)
    at util.js:654:12
    at Array.map (native)
    at formatObject (util.js:653:15)
    at formatValue (util.js:592:16)
    at formatProperty (util.js:792:15)
    at util.js:654:12
    at Array.map (native)
    at formatObject (util.js:653:15)
    at formatValue (util.js:592:16)
    at formatProperty (util.js:792:15)
    at util.js:654:12
    at Array.map (native)
{ Error: write ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:801:14) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'write' }
{ Error: write ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:801:14) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'write' }
{ Error: write ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:801:14) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'write' }
{ Error: write ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:801:14) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'write' }
{ Error: write ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:801:14) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'write' }
{ Error: write ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:801:14) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'write' }
