### ISSUE TITLE
[bug] Error: Incomplete character sequence (decoding `Iconv` issue)

### ISSUE THREAD

**Issue by niftylettuce** [nodemailer/mailparser#261]
Possibly related to #258.

I've tested this against a huge dataset (50GB+) and found a few issues (possibly could be actually badly formatted messages, not sure - I figured you would know best @andris9).

I'm using default `mailparser.simpleParser` options with `Iconv` library as the `Iconv` option, e.g. `const { Iconv } = require('iconv');`.

The attached messages cause this error:

```sh
Error: Incomplete character sequence.
    at errnoException (/Users/anonymous/Projects/project/node_modules/iconv/lib/iconv.js:182:13)
    at convert (/Users/anonymous/Projects/project/node_modules/iconv/lib/iconv.js:106:11)
    at Iconv.write (/Users/anonymous/Projects/project/node_modules/iconv/lib/iconv.js:72:17)
    at Iconv.end (/Users/anonymous/Projects/project/node_modules/iconv/lib/iconv.js:88:10)
    at IconvDecoder._flush (/Users/jack/Projects/project/node_modules/mailparser/lib/mail-parser.js:80:21)
    at IconvDecoder.prefinish (_stream_transform.js:142:10)
    at IconvDecoder.emit (events.js:311:20)
    at prefinish (_stream_writable.js:676:14)
    at finishMaybe (_stream_writable.js:684:5)
    at endWritable (_stream_writable.js:704:3) {
  code: 'EINVAL'
}
```

Using latest version of `mailparser` as well as `iconv`.

[bug-report.zip](https://github.com/nodemailer/mailparser/files/4528142/bug-report.zip)

**Comment by andris9** [comment]
Iconv was added mostly because iconv-lite did not support some required Japanese charsets. Mailparser is now able to handle these charsets without Iconv so the quick "fix" would be to drop using Iconv. For actual a fix an input would be needed, that triggers that error, preferably a broken unit test.
