### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to decode base64

### ISSUE THREAD

**Issue by pravinkanna** [nodemailer/mailparser#381]
I am facing this error while trying to parse the MIME using `simpleParser`.

Error:
```
error: Uncaught InvalidCharacterError: Failed to decode base64
    at forgivingBase64Decode (ext:deno_web/00_infra.js:257:10)
    at base64ToBytes (ext:deno_node/internal_binding/_utils.ts:19:12)
    at Uint8Array.base64Write (ext:deno_node/internal/buffer.mjs:781:21)
    at Object.write (ext:deno_node/internal/buffer.mjs:2205:46)
    at Uint8Array.write (ext:deno_node/internal/buffer.mjs:905:14)
    at fromString (ext:deno_node/internal/buffer.mjs:286:22)
    at _from (ext:deno_node/internal/buffer.mjs:186:12)
    at Function.from (ext:deno_node/internal/buffer.mjs:229:10)
    at decode (file:///tmp/deno-compile-main-create-batch-files/.deno_compile_node_modules/localhost/libbase64/1.3.0/lib/libbase64.js:29:19)
    at Decoder._transform (file:///tmp/deno-compile-main-create-batch-files/.deno_compile_node_modules/localhost/libbase64/1.3.0/lib/libbase64.js:227:23)
```

**Comment by andris9** [comment]
Mailparser is not guaranteed to run on any other platform than Node. You seem to be using Deno.
